import type { NutrientProfile } from '../../../types/recipe'

// AAFCO Dog/Cat Food Nutrient Profiles (2014 proposed revisions, Model Bills
// 2015). 단계 1-A 확장 (DL-032). 자료원: AAFCO Nutrient Profiles BASED ON
// CALORIE CONTENT (per 1000 kcal ME) 표. perMe=원본, perDm=perMe×0.4
// (AAFCO 4000 kcal/kg DM 가정). selenium/B9/B12/B7/K는 mg→µg(×1000) 변환.
// 고양이 taurine/copper는 extruded(건식) 기준. calcium 상한은 대형견(b) 4.5가
// 아닌 일반 6.25 사용(주석). 고양이 Ca/P는 calorie 표 미수록이라 생략.

export const AAFCO_PROFILES: NutrientProfile[] = [
  {
    id: 'AAFCO_2014_DOG_GROWTH',
    standard: 'AAFCO', year: 2014, species: 'dog', lifeStage: 'early_growth_repro',
    label: '강아지 성장·번식 (AAFCO)',
    perMe: {
      crudeProtein: { min: 56.3 },
      crudeFat: { min: 21.3 },
      arginine: { min: 2.5 },
      histidine: { min: 1.1 },
      isoleucine: { min: 1.78 },
      leucine: { min: 3.23 },
      lysine: { min: 2.25 },
      methionine: { min: 0.88 },
      methionineCystine: { min: 1.75 },
      phenylalanine: { min: 2.08 },
      phenylalanineTyrosine: { min: 3.25 },
      threonine: { min: 2.6 },
      tryptophan: { min: 0.5 },
      valine: { min: 1.7 },
      linoleicAcid: { min: 3.3 },
      alphaLinolenicAcid: { min: 0.2 },
      calcium: { min: 3, max: 6.25, maxType: 'nutritional' },
      phosphorus: { min: 2.5, max: 4, maxType: 'nutritional' },
      potassium: { min: 1.5 },
      sodium: { min: 0.8 },
      chloride: { min: 1.1 },
      magnesium: { min: 0.15 },
      copper: { min: 3.1 },
      iodine: { min: 0.25, max: 2.75, maxType: 'nutritional' },
      iron: { min: 22 },
      manganese: { min: 1.8 },
      selenium: { min: 90, max: 500, maxType: 'nutritional' },
      zinc: { min: 25 },
      vitaminA: { min: 1250, max: 62500, maxType: 'nutritional' },
      vitaminD: { min: 125, max: 750, maxType: 'nutritional' },
      vitaminE: { min: 12.5 },
      vitaminB1: { min: 0.56 },
      vitaminB2: { min: 1.3 },
      vitaminB3: { min: 3.4 },
      vitaminB5: { min: 3 },
      vitaminB6: { min: 0.38 },
      vitaminB9: { min: 54 },
      vitaminB12: { min: 7 },
      choline: { min: 340 },
    },
    perDm: {
      crudeProtein: { min: 22.52 },
      crudeFat: { min: 8.52 },
      arginine: { min: 1 },
      histidine: { min: 0.44 },
      isoleucine: { min: 0.712 },
      leucine: { min: 1.292 },
      lysine: { min: 0.9 },
      methionine: { min: 0.352 },
      methionineCystine: { min: 0.7 },
      phenylalanine: { min: 0.832 },
      phenylalanineTyrosine: { min: 1.3 },
      threonine: { min: 1.04 },
      tryptophan: { min: 0.2 },
      valine: { min: 0.68 },
      linoleicAcid: { min: 1.32 },
      alphaLinolenicAcid: { min: 0.08 },
      calcium: { min: 1.2, max: 2.5, maxType: 'nutritional' },
      phosphorus: { min: 1, max: 1.6, maxType: 'nutritional' },
      potassium: { min: 0.6 },
      sodium: { min: 0.32 },
      chloride: { min: 0.44 },
      magnesium: { min: 0.06 },
      copper: { min: 1.24 },
      iodine: { min: 0.1, max: 1.1, maxType: 'nutritional' },
      iron: { min: 8.8 },
      manganese: { min: 0.72 },
      selenium: { min: 36, max: 200, maxType: 'nutritional' },
      zinc: { min: 10 },
      vitaminA: { min: 500, max: 25000, maxType: 'nutritional' },
      vitaminD: { min: 50, max: 300, maxType: 'nutritional' },
      vitaminE: { min: 5 },
      vitaminB1: { min: 0.224 },
      vitaminB2: { min: 0.52 },
      vitaminB3: { min: 1.36 },
      vitaminB5: { min: 1.2 },
      vitaminB6: { min: 0.152 },
      vitaminB9: { min: 21.6 },
      vitaminB12: { min: 2.8 },
      choline: { min: 136 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'AAFCO_2014_DOG_ADULT',
    standard: 'AAFCO', year: 2014, species: 'dog', lifeStage: 'adult',
    label: '성견 유지 (AAFCO)',
    perMe: {
      crudeProtein: { min: 45 },
      crudeFat: { min: 13.8 },
      arginine: { min: 1.28 },
      histidine: { min: 0.48 },
      isoleucine: { min: 0.95 },
      leucine: { min: 1.7 },
      lysine: { min: 1.58 },
      methionine: { min: 0.83 },
      methionineCystine: { min: 1.63 },
      phenylalanine: { min: 1.13 },
      phenylalanineTyrosine: { min: 1.85 },
      threonine: { min: 1.2 },
      tryptophan: { min: 0.4 },
      valine: { min: 1.23 },
      linoleicAcid: { min: 2.8 },
      calcium: { min: 1.25, max: 6.25, maxType: 'nutritional' },
      phosphorus: { min: 1, max: 4, maxType: 'nutritional' },
      potassium: { min: 1.5 },
      sodium: { min: 0.2 },
      chloride: { min: 0.3 },
      magnesium: { min: 0.15 },
      copper: { min: 1.83 },
      iodine: { min: 0.25, max: 2.75, maxType: 'nutritional' },
      iron: { min: 10 },
      manganese: { min: 1.25 },
      selenium: { min: 80, max: 500, maxType: 'nutritional' },
      zinc: { min: 20 },
      vitaminA: { min: 1250, max: 62500, maxType: 'nutritional' },
      vitaminD: { min: 125, max: 750, maxType: 'nutritional' },
      vitaminE: { min: 12.5 },
      vitaminB1: { min: 0.56 },
      vitaminB2: { min: 1.3 },
      vitaminB3: { min: 3.4 },
      vitaminB5: { min: 3 },
      vitaminB6: { min: 0.38 },
      vitaminB9: { min: 54 },
      vitaminB12: { min: 7 },
      choline: { min: 340 },
    },
    perDm: {
      crudeProtein: { min: 18 },
      crudeFat: { min: 5.52 },
      arginine: { min: 0.512 },
      histidine: { min: 0.192 },
      isoleucine: { min: 0.38 },
      leucine: { min: 0.68 },
      lysine: { min: 0.632 },
      methionine: { min: 0.332 },
      methionineCystine: { min: 0.652 },
      phenylalanine: { min: 0.452 },
      phenylalanineTyrosine: { min: 0.74 },
      threonine: { min: 0.48 },
      tryptophan: { min: 0.16 },
      valine: { min: 0.492 },
      linoleicAcid: { min: 1.12 },
      calcium: { min: 0.5, max: 2.5, maxType: 'nutritional' },
      phosphorus: { min: 0.4, max: 1.6, maxType: 'nutritional' },
      potassium: { min: 0.6 },
      sodium: { min: 0.08 },
      chloride: { min: 0.12 },
      magnesium: { min: 0.06 },
      copper: { min: 0.732 },
      iodine: { min: 0.1, max: 1.1, maxType: 'nutritional' },
      iron: { min: 4 },
      manganese: { min: 0.5 },
      selenium: { min: 32, max: 200, maxType: 'nutritional' },
      zinc: { min: 8 },
      vitaminA: { min: 500, max: 25000, maxType: 'nutritional' },
      vitaminD: { min: 50, max: 300, maxType: 'nutritional' },
      vitaminE: { min: 5 },
      vitaminB1: { min: 0.224 },
      vitaminB2: { min: 0.52 },
      vitaminB3: { min: 1.36 },
      vitaminB5: { min: 1.2 },
      vitaminB6: { min: 0.152 },
      vitaminB9: { min: 21.6 },
      vitaminB12: { min: 2.8 },
      choline: { min: 136 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'AAFCO_2014_CAT_GROWTH',
    standard: 'AAFCO', year: 2014, species: 'cat', lifeStage: 'early_growth_repro',
    label: '고양이 성장·번식 (AAFCO)',
    perMe: {
      crudeProtein: { min: 75 },
      crudeFat: { min: 22.5 },
      arginine: { min: 3.1 },
      histidine: { min: 0.83 },
      isoleucine: { min: 1.4 },
      leucine: { min: 3.2 },
      lysine: { min: 3 },
      methionine: { min: 1.55, max: 3.75, maxType: 'nutritional' },
      methionineCystine: { min: 2.75 },
      phenylalanine: { min: 1.3 },
      phenylalanineTyrosine: { min: 4.8 },
      threonine: { min: 1.83 },
      tryptophan: { min: 0.63, max: 4.25, maxType: 'nutritional' },
      valine: { min: 1.55 },
      taurine: { min: 0.25 },
      linoleicAcid: { min: 1.4 },
      arachidonicAcid: { min: 0.05 },
      alphaLinolenicAcid: { min: 0.05 },
      calcium: { min: 2.5 },
      phosphorus: { min: 2 },
      potassium: { min: 1.5 },
      sodium: { min: 0.5 },
      chloride: { min: 0.75 },
      magnesium: { min: 0.2 },
      copper: { min: 3.75 },
      iodine: { min: 0.45 },
      iron: { min: 20 },
      manganese: { min: 1.9 },
      selenium: { min: 75 },
      zinc: { min: 18.8 },
      vitaminA: { min: 1667, max: 83325, maxType: 'nutritional' },
      vitaminD: { min: 70, max: 7520, maxType: 'nutritional' },
      vitaminE: { min: 10 },
      vitaminB1: { min: 1.4 },
      vitaminB2: { min: 1 },
      vitaminB3: { min: 15 },
      vitaminB5: { min: 1.44 },
      vitaminB6: { min: 1 },
      vitaminB7: { min: 18 },
      vitaminB9: { min: 200 },
      vitaminB12: { min: 5 },
      choline: { min: 600 },
      vitaminK: { min: 25 },
    },
    perDm: {
      crudeProtein: { min: 30 },
      crudeFat: { min: 9 },
      arginine: { min: 1.24 },
      histidine: { min: 0.332 },
      isoleucine: { min: 0.56 },
      leucine: { min: 1.28 },
      lysine: { min: 1.2 },
      methionine: { min: 0.62, max: 1.5, maxType: 'nutritional' },
      methionineCystine: { min: 1.1 },
      phenylalanine: { min: 0.52 },
      phenylalanineTyrosine: { min: 1.92 },
      threonine: { min: 0.732 },
      tryptophan: { min: 0.252, max: 1.7, maxType: 'nutritional' },
      valine: { min: 0.62 },
      taurine: { min: 0.1 },
      linoleicAcid: { min: 0.56 },
      arachidonicAcid: { min: 0.02 },
      alphaLinolenicAcid: { min: 0.02 },
      calcium: { min: 1 },
      phosphorus: { min: 0.8 },
      potassium: { min: 0.6 },
      sodium: { min: 0.2 },
      chloride: { min: 0.3 },
      magnesium: { min: 0.08 },
      copper: { min: 1.5 },
      iodine: { min: 0.18 },
      iron: { min: 8 },
      manganese: { min: 0.76 },
      selenium: { min: 30 },
      zinc: { min: 7.52 },
      vitaminA: { min: 666.8, max: 33330, maxType: 'nutritional' },
      vitaminD: { min: 28, max: 3008, maxType: 'nutritional' },
      vitaminE: { min: 4 },
      vitaminB1: { min: 0.56 },
      vitaminB2: { min: 0.4 },
      vitaminB3: { min: 6 },
      vitaminB5: { min: 0.576 },
      vitaminB6: { min: 0.4 },
      vitaminB7: { min: 7.2 },
      vitaminB9: { min: 80 },
      vitaminB12: { min: 2 },
      choline: { min: 240 },
      vitaminK: { min: 10 },
    },
  },
  {
    id: 'AAFCO_2014_CAT_ADULT',
    standard: 'AAFCO', year: 2014, species: 'cat', lifeStage: 'adult',
    label: '성묘 유지 (AAFCO)',
    perMe: {
      crudeProtein: { min: 65 },
      crudeFat: { min: 22.5 },
      arginine: { min: 2.6 },
      histidine: { min: 0.78 },
      isoleucine: { min: 1.3 },
      leucine: { min: 3.1 },
      lysine: { min: 2.08 },
      methionine: { min: 0.5, max: 3.75, maxType: 'nutritional' },
      methionineCystine: { min: 1 },
      phenylalanine: { min: 1.05 },
      phenylalanineTyrosine: { min: 3.83 },
      threonine: { min: 1.83 },
      tryptophan: { min: 0.4, max: 4.25, maxType: 'nutritional' },
      valine: { min: 1.55 },
      taurine: { min: 0.25 },
      linoleicAcid: { min: 1.4 },
      arachidonicAcid: { min: 0.05 },
      calcium: { min: 1.5 },
      phosphorus: { min: 1.25 },
      potassium: { min: 1.5 },
      sodium: { min: 0.5 },
      chloride: { min: 0.75 },
      magnesium: { min: 0.1 },
      copper: { min: 1.25 },
      iodine: { min: 0.15 },
      iron: { min: 20 },
      manganese: { min: 1.9 },
      selenium: { min: 75 },
      zinc: { min: 18.8 },
      vitaminA: { min: 833, max: 83325, maxType: 'nutritional' },
      vitaminD: { min: 70, max: 7520, maxType: 'nutritional' },
      vitaminE: { min: 10 },
      vitaminB1: { min: 1.4 },
      vitaminB2: { min: 1 },
      vitaminB3: { min: 15 },
      vitaminB5: { min: 1.44 },
      vitaminB6: { min: 1 },
      vitaminB7: { min: 18 },
      vitaminB9: { min: 200 },
      vitaminB12: { min: 5 },
      choline: { min: 600 },
      vitaminK: { min: 25 },
    },
    perDm: {
      crudeProtein: { min: 26 },
      crudeFat: { min: 9 },
      arginine: { min: 1.04 },
      histidine: { min: 0.312 },
      isoleucine: { min: 0.52 },
      leucine: { min: 1.24 },
      lysine: { min: 0.832 },
      methionine: { min: 0.2, max: 1.5, maxType: 'nutritional' },
      methionineCystine: { min: 0.4 },
      phenylalanine: { min: 0.42 },
      phenylalanineTyrosine: { min: 1.532 },
      threonine: { min: 0.732 },
      tryptophan: { min: 0.16, max: 1.7, maxType: 'nutritional' },
      valine: { min: 0.62 },
      taurine: { min: 0.1 },
      linoleicAcid: { min: 0.56 },
      arachidonicAcid: { min: 0.02 },
      calcium: { min: 0.6 },
      phosphorus: { min: 0.5 },
      potassium: { min: 0.6 },
      sodium: { min: 0.2 },
      chloride: { min: 0.3 },
      magnesium: { min: 0.04 },
      copper: { min: 0.5 },
      iodine: { min: 0.06 },
      iron: { min: 8 },
      manganese: { min: 0.76 },
      selenium: { min: 30 },
      zinc: { min: 7.52 },
      vitaminA: { min: 333.2, max: 33330, maxType: 'nutritional' },
      vitaminD: { min: 28, max: 3008, maxType: 'nutritional' },
      vitaminE: { min: 4 },
      vitaminB1: { min: 0.56 },
      vitaminB2: { min: 0.4 },
      vitaminB3: { min: 6 },
      vitaminB5: { min: 0.576 },
      vitaminB6: { min: 0.4 },
      vitaminB7: { min: 7.2 },
      vitaminB9: { min: 80 },
      vitaminB12: { min: 2 },
      choline: { min: 240 },
      vitaminK: { min: 10 },
    },
  },
]
