import type { NutrientProfile } from '../../../types/recipe'

// FEDIAF 2025 영양 표준 (단계 1-A, DL-032). 자료원: FEDIAF Nutritional
// Guidelines 2025, Table III-3a/b(개)·III-4a/b(고양이). 좌표 추출 전사.
// perMe=per 1000 kcal ME, perDm=per 100 g DM. 성체 MER 2종 모두 적재.
// 고양이 성장/번식 상이 영양소는 보수적으로 번식(높은) 값. taurine/selenium
// 은 건식 기준. EU 법적상한(legal)은 DM basis만. calcium 후기성장은 대형견(b).

export const FEDIAF_2025_PROFILES: NutrientProfile[] = [
  {
    id: 'FEDIAF_2025_DOG_ADULT_MER95',
    standard: 'FEDIAF', year: 2025, species: 'dog', lifeStage: 'adult',
    label: '성견 유지 (MER 95)', mer: '95 kcal/kg^0.75',
    perMe: {
      crudeProtein: { min: 52.1 },
      crudeFat: { min: 13.75 },
      arginine: { min: 1.51 },
      histidine: { min: 0.67 },
      isoleucine: { min: 1.33 },
      leucine: { min: 2.37 },
      lysine: { min: 1.22 },
      methionine: { min: 1.16 },
      methionineCystine: { min: 2.21 },
      phenylalanine: { min: 1.56 },
      phenylalanineTyrosine: { min: 2.58 },
      threonine: { min: 1.51 },
      tryptophan: { min: 0.49 },
      valine: { min: 1.71 },
      linoleicAcid: { min: 3.82 },
      calcium: { min: 1.45, max: 6.25, maxType: 'nutritional' },
      phosphorus: { min: 1.16, max: 4, maxType: 'nutritional' },
      potassium: { min: 1.45 },
      sodium: { min: 0.29 },
      chloride: { min: 0.43 },
      magnesium: { min: 0.2 },
      copper: { min: 2.08 },
      iodine: { min: 0.3 },
      iron: { min: 10.4 },
      manganese: { min: 1.67 },
      zinc: { min: 20.8 },
      vitaminA: { min: 1754 },
      vitaminD: { min: 159 },
      vitaminE: { min: 10.4 },
      vitaminB1: { min: 0.62 },
      vitaminB2: { min: 1.74 },
      vitaminB3: { min: 4.74 },
      vitaminB5: { min: 4.11 },
      vitaminB6: { min: 0.42 },
      vitaminB9: { min: 74.7 },
      vitaminB12: { min: 9.68 },
      choline: { min: 474 },
    },
    perDm: {
      crudeProtein: { min: 21 },
      crudeFat: { min: 5.5 },
      arginine: { min: 0.6 },
      histidine: { min: 0.27 },
      isoleucine: { min: 0.53 },
      leucine: { min: 0.95 },
      lysine: { min: 0.46 },
      methionine: { min: 0.46 },
      methionineCystine: { min: 0.88 },
      phenylalanine: { min: 0.63 },
      phenylalanineTyrosine: { min: 1.03 },
      threonine: { min: 0.6 },
      tryptophan: { min: 0.2 },
      valine: { min: 0.68 },
      linoleicAcid: { min: 1.53 },
      calcium: { min: 0.58, max: 2.5, maxType: 'nutritional' },
      phosphorus: { min: 0.46, max: 1.6, maxType: 'nutritional' },
      potassium: { min: 0.58 },
      sodium: { min: 0.12 },
      chloride: { min: 0.17 },
      magnesium: { min: 0.08 },
      copper: { min: 0.83, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.12, max: 1.1, maxType: 'legal' },
      iron: { min: 4.17, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.67, max: 17, maxType: 'legal' },
      zinc: { min: 8.34, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 702 },
      vitaminD: { min: 63.9 },
      vitaminE: { min: 4.17 },
      vitaminB1: { min: 0.25 },
      vitaminB2: { min: 0.69 },
      vitaminB3: { min: 1.89 },
      vitaminB5: { min: 1.64 },
      vitaminB6: { min: 0.17 },
      vitaminB9: { min: 29.9 },
      vitaminB12: { min: 3.87 },
      choline: { min: 189 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'FEDIAF_2025_DOG_ADULT_MER110',
    standard: 'FEDIAF', year: 2025, species: 'dog', lifeStage: 'adult',
    label: '성견 유지 (MER 110)', mer: '110 kcal/kg^0.75',
    perMe: {
      crudeProtein: { min: 45 },
      crudeFat: { min: 13.75 },
      arginine: { min: 1.3 },
      histidine: { min: 0.58 },
      isoleucine: { min: 1.15 },
      leucine: { min: 2.05 },
      lysine: { min: 1.05 },
      methionine: { min: 1 },
      methionineCystine: { min: 1.91 },
      phenylalanine: { min: 1.35 },
      phenylalanineTyrosine: { min: 2.23 },
      threonine: { min: 1.3 },
      tryptophan: { min: 0.43 },
      valine: { min: 1.48 },
      linoleicAcid: { min: 3.27 },
      calcium: { min: 1.25, max: 6.25, maxType: 'nutritional' },
      phosphorus: { min: 1, max: 4, maxType: 'nutritional' },
      potassium: { min: 1.25 },
      sodium: { min: 0.25 },
      chloride: { min: 0.38 },
      magnesium: { min: 0.18 },
      copper: { min: 1.8 },
      iodine: { min: 0.26 },
      iron: { min: 9 },
      manganese: { min: 1.44 },
      zinc: { min: 18 },
      vitaminA: { min: 1515 },
      vitaminD: { min: 138 },
      vitaminE: { min: 9 },
      vitaminB1: { min: 0.54 },
      vitaminB2: { min: 1.5 },
      vitaminB3: { min: 4.09 },
      vitaminB5: { min: 3.55 },
      vitaminB6: { min: 0.36 },
      vitaminB9: { min: 64.5 },
      vitaminB12: { min: 8.36 },
      choline: { min: 409 },
    },
    perDm: {
      crudeProtein: { min: 18 },
      crudeFat: { min: 5.5 },
      arginine: { min: 0.52 },
      histidine: { min: 0.23 },
      isoleucine: { min: 0.46 },
      leucine: { min: 0.82 },
      lysine: { min: 0.42 },
      methionine: { min: 0.4 },
      methionineCystine: { min: 0.76 },
      phenylalanine: { min: 0.54 },
      phenylalanineTyrosine: { min: 0.89 },
      threonine: { min: 0.52 },
      tryptophan: { min: 0.17 },
      valine: { min: 0.59 },
      linoleicAcid: { min: 1.32 },
      calcium: { min: 0.5, max: 2.5, maxType: 'nutritional' },
      phosphorus: { min: 0.4, max: 1.6, maxType: 'nutritional' },
      potassium: { min: 0.5 },
      sodium: { min: 0.1 },
      chloride: { min: 0.15 },
      magnesium: { min: 0.07 },
      copper: { min: 0.72, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.11, max: 1.1, maxType: 'legal' },
      iron: { min: 3.6, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.58, max: 17, maxType: 'legal' },
      zinc: { min: 7.2, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 606 },
      vitaminD: { min: 55.2 },
      vitaminE: { min: 3.6 },
      vitaminB1: { min: 0.21 },
      vitaminB2: { min: 0.6 },
      vitaminB3: { min: 1.64 },
      vitaminB5: { min: 1.42 },
      vitaminB6: { min: 0.15 },
      vitaminB9: { min: 25.8 },
      vitaminB12: { min: 3.35 },
      choline: { min: 164 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'FEDIAF_2025_DOG_EARLY_GROWTH_REPRO',
    standard: 'FEDIAF', year: 2025, species: 'dog', lifeStage: 'early_growth_repro',
    label: '강아지 초기성장·번식 (<14주)',
    perMe: {
      crudeProtein: { min: 62.5 },
      crudeFat: { min: 21.25 },
      arginine: { min: 2.04 },
      histidine: { min: 0.98 },
      isoleucine: { min: 1.63 },
      leucine: { min: 3.23 },
      lysine: { min: 2.2 },
      methionine: { min: 0.88 },
      methionineCystine: { min: 1.75 },
      phenylalanine: { min: 1.63 },
      phenylalanineTyrosine: { min: 3.25 },
      threonine: { min: 2.03 },
      tryptophan: { min: 0.58 },
      valine: { min: 1.7 },
      linoleicAcid: { min: 3.25 },
      arachidonicAcid: { min: 75 },
      alphaLinolenicAcid: { min: 0.2 },
      epaDha: { min: 0.13 },
      calcium: { min: 2.5, max: 4, maxType: 'nutritional' },
      phosphorus: { min: 2.25 },
      potassium: { min: 1.1 },
      sodium: { min: 0.55 },
      chloride: { min: 0.83 },
      magnesium: { min: 0.1 },
      copper: { min: 2.75 },
      iodine: { min: 0.38 },
      iron: { min: 22 },
      manganese: { min: 1.4 },
      zinc: { min: 25 },
      vitaminA: { min: 1250 },
      vitaminD: { min: 138 },
      vitaminE: { min: 12.5 },
      vitaminB1: { min: 0.45 },
      vitaminB2: { min: 1.05 },
      vitaminB3: { min: 3.4 },
      vitaminB5: { min: 3 },
      vitaminB6: { min: 0.3 },
      vitaminB9: { min: 54 },
      vitaminB12: { min: 7 },
      choline: { min: 425 },
    },
    perDm: {
      crudeProtein: { min: 25 },
      crudeFat: { min: 8.5 },
      arginine: { min: 0.82 },
      histidine: { min: 0.39 },
      isoleucine: { min: 0.65 },
      leucine: { min: 1.29 },
      lysine: { min: 0.88 },
      methionine: { min: 0.35 },
      methionineCystine: { min: 0.7 },
      phenylalanine: { min: 0.65 },
      phenylalanineTyrosine: { min: 1.3 },
      threonine: { min: 0.81 },
      tryptophan: { min: 0.23 },
      valine: { min: 0.68 },
      linoleicAcid: { min: 1.3 },
      arachidonicAcid: { min: 30 },
      alphaLinolenicAcid: { min: 0.08 },
      epaDha: { min: 0.05 },
      calcium: { min: 1, max: 1.6, maxType: 'nutritional' },
      phosphorus: { min: 0.9 },
      potassium: { min: 0.44 },
      sodium: { min: 0.22 },
      chloride: { min: 0.33 },
      magnesium: { min: 0.04 },
      copper: { min: 1.1, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.15, max: 1.1, maxType: 'legal' },
      iron: { min: 8.8, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.56, max: 17, maxType: 'legal' },
      zinc: { min: 10, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 500 },
      vitaminD: { min: 55.2 },
      vitaminE: { min: 5 },
      vitaminB1: { min: 0.18 },
      vitaminB2: { min: 0.42 },
      vitaminB3: { min: 1.36 },
      vitaminB5: { min: 1.2 },
      vitaminB6: { min: 0.12 },
      vitaminB9: { min: 21.6 },
      vitaminB12: { min: 2.8 },
      choline: { min: 170 },
    },
    ratios: { caP: { min: 1, max: 1.6 } },
  },
  {
    id: 'FEDIAF_2025_DOG_LATE_GROWTH',
    standard: 'FEDIAF', year: 2025, species: 'dog', lifeStage: 'late_growth',
    label: '강아지 후기성장 (≥14주)',
    perMe: {
      crudeProtein: { min: 50 },
      crudeFat: { min: 21.25 },
      arginine: { min: 1.84 },
      histidine: { min: 0.63 },
      isoleucine: { min: 1.25 },
      leucine: { min: 2 },
      lysine: { min: 1.75 },
      methionine: { min: 0.65 },
      methionineCystine: { min: 1.33 },
      phenylalanine: { min: 1.25 },
      phenylalanineTyrosine: { min: 2.5 },
      threonine: { min: 1.6 },
      tryptophan: { min: 0.53 },
      valine: { min: 1.4 },
      linoleicAcid: { min: 3.25 },
      arachidonicAcid: { min: 75 },
      alphaLinolenicAcid: { min: 0.2 },
      epaDha: { min: 0.13 },
      calcium: { min: 2.5, max: 4.5, maxType: 'nutritional' },
      phosphorus: { min: 1.75 },
      potassium: { min: 1.1 },
      sodium: { min: 0.55 },
      chloride: { min: 0.83 },
      magnesium: { min: 0.1 },
      copper: { min: 2.75 },
      iodine: { min: 0.38 },
      iron: { min: 22 },
      manganese: { min: 1.4 },
      zinc: { min: 25 },
      vitaminA: { min: 1250 },
      vitaminD: { min: 125 },
      vitaminE: { min: 12.5 },
      vitaminB1: { min: 0.45 },
      vitaminB2: { min: 1.05 },
      vitaminB3: { min: 3.4 },
      vitaminB5: { min: 3 },
      vitaminB6: { min: 0.3 },
      vitaminB9: { min: 54 },
      vitaminB12: { min: 7 },
      choline: { min: 425 },
    },
    perDm: {
      crudeProtein: { min: 20 },
      crudeFat: { min: 8.5 },
      arginine: { min: 0.74 },
      histidine: { min: 0.25 },
      isoleucine: { min: 0.5 },
      leucine: { min: 0.8 },
      lysine: { min: 0.7 },
      methionine: { min: 0.26 },
      methionineCystine: { min: 0.53 },
      phenylalanine: { min: 0.5 },
      phenylalanineTyrosine: { min: 1 },
      threonine: { min: 0.64 },
      tryptophan: { min: 0.21 },
      valine: { min: 0.56 },
      linoleicAcid: { min: 1.3 },
      arachidonicAcid: { min: 30 },
      alphaLinolenicAcid: { min: 0.08 },
      epaDha: { min: 0.05 },
      calcium: { min: 1, max: 1.8, maxType: 'nutritional' },
      phosphorus: { min: 0.7 },
      potassium: { min: 0.44 },
      sodium: { min: 0.22 },
      chloride: { min: 0.33 },
      magnesium: { min: 0.04 },
      copper: { min: 1.1, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.15, max: 1.1, maxType: 'legal' },
      iron: { min: 8.8, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.56, max: 17, maxType: 'legal' },
      zinc: { min: 10, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 500 },
      vitaminD: { min: 50 },
      vitaminE: { min: 5 },
      vitaminB1: { min: 0.18 },
      vitaminB2: { min: 0.42 },
      vitaminB3: { min: 1.36 },
      vitaminB5: { min: 1.2 },
      vitaminB6: { min: 0.12 },
      vitaminB9: { min: 21.6 },
      vitaminB12: { min: 2.8 },
      choline: { min: 170 },
    },
    ratios: { caP: { min: 1, max: 1.8 } },
  },
  {
    id: 'FEDIAF_2025_CAT_ADULT_MER75',
    standard: 'FEDIAF', year: 2025, species: 'cat', lifeStage: 'adult',
    label: '성묘 유지 (MER 75)', mer: '75 kcal/kg^0.67',
    perMe: {
      crudeProtein: { min: 83.3 },
      crudeFat: { min: 22.5 },
      arginine: { min: 3.3 },
      histidine: { min: 0.87 },
      isoleucine: { min: 1.44 },
      leucine: { min: 3.4 },
      lysine: { min: 1.13 },
      methionine: { min: 0.57 },
      methionineCystine: { min: 1.13 },
      phenylalanine: { min: 1.33 },
      phenylalanineTyrosine: { min: 5.11 },
      threonine: { min: 1.73 },
      tryptophan: { min: 0.44 },
      valine: { min: 1.7 },
      taurine: { min: 0.33 },
      linoleicAcid: { min: 1.67 },
      arachidonicAcid: { min: 20 },
      calcium: { min: 1.33 },
      phosphorus: { min: 0.85 },
      potassium: { min: 2 },
      sodium: { min: 0.25 },
      chloride: { min: 0.39 },
      magnesium: { min: 0.13 },
      copper: { min: 1.67 },
      iodine: { min: 0.43 },
      iron: { min: 26.7 },
      manganese: { min: 1.67 },
      selenium: { min: 70 },
      zinc: { min: 25 },
      vitaminA: { min: 1110 },
      vitaminD: { min: 83.3 },
      vitaminE: { min: 12.7 },
      vitaminB1: { min: 1.47 },
      vitaminB2: { min: 1.05 },
      vitaminB3: { min: 10.5 },
      vitaminB5: { min: 1.92 },
      vitaminB6: { min: 0.83 },
      vitaminB7: { min: 20 },
      vitaminB9: { min: 253 },
      vitaminB12: { min: 5.87 },
      choline: { min: 800 },
    },
    perDm: {
      crudeProtein: { min: 33.3 },
      crudeFat: { min: 9 },
      arginine: { min: 1.3 },
      histidine: { min: 0.35 },
      isoleucine: { min: 0.57 },
      leucine: { min: 1.36 },
      lysine: { min: 0.45 },
      methionine: { min: 0.23 },
      methionineCystine: { min: 0.45 },
      phenylalanine: { min: 0.53 },
      phenylalanineTyrosine: { min: 2.04 },
      threonine: { min: 0.69 },
      tryptophan: { min: 0.17 },
      valine: { min: 0.68 },
      taurine: { min: 0.13 },
      linoleicAcid: { min: 0.67 },
      arachidonicAcid: { min: 8 },
      calcium: { min: 0.53 },
      phosphorus: { min: 0.35 },
      potassium: { min: 0.8 },
      sodium: { min: 0.1 },
      chloride: { min: 0.15 },
      magnesium: { min: 0.05 },
      copper: { min: 0.67, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.17, max: 1.1, maxType: 'legal' },
      iron: { min: 10.7, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.67, max: 17, maxType: 'legal' },
      selenium: { min: 28, max: 56.8, maxType: 'legal' },
      zinc: { min: 10, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 444 },
      vitaminD: { min: 33.3 },
      vitaminE: { min: 5.07 },
      vitaminB1: { min: 0.59 },
      vitaminB2: { min: 0.42 },
      vitaminB3: { min: 4.21 },
      vitaminB5: { min: 0.77 },
      vitaminB6: { min: 0.33 },
      vitaminB7: { min: 8 },
      vitaminB9: { min: 101 },
      vitaminB12: { min: 2.35 },
      choline: { min: 320 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'FEDIAF_2025_CAT_ADULT_MER100',
    standard: 'FEDIAF', year: 2025, species: 'cat', lifeStage: 'adult',
    label: '성묘 유지 (MER 100)', mer: '100 kcal/kg^0.67',
    perMe: {
      crudeProtein: { min: 62.5 },
      crudeFat: { min: 22.5 },
      arginine: { min: 2.5 },
      histidine: { min: 0.65 },
      isoleucine: { min: 1.08 },
      leucine: { min: 2.55 },
      lysine: { min: 0.85 },
      methionine: { min: 0.43 },
      methionineCystine: { min: 0.85 },
      phenylalanine: { min: 1 },
      phenylalanineTyrosine: { min: 3.83 },
      threonine: { min: 1.3 },
      tryptophan: { min: 0.33 },
      valine: { min: 1.28 },
      taurine: { min: 0.25 },
      linoleicAcid: { min: 1.25 },
      arachidonicAcid: { min: 15 },
      calcium: { min: 1 },
      phosphorus: { min: 0.64 },
      potassium: { min: 1.5 },
      sodium: { min: 0.19 },
      chloride: { min: 0.29 },
      magnesium: { min: 0.1 },
      copper: { min: 1.25 },
      iodine: { min: 0.33 },
      iron: { min: 20 },
      manganese: { min: 1.25 },
      selenium: { min: 52.5 },
      zinc: { min: 18.8 },
      vitaminA: { min: 833 },
      vitaminD: { min: 62.5 },
      vitaminE: { min: 9.5 },
      vitaminB1: { min: 1.1 },
      vitaminB2: { min: 0.8 },
      vitaminB3: { min: 8 },
      vitaminB5: { min: 1.44 },
      vitaminB6: { min: 0.63 },
      vitaminB7: { min: 15 },
      vitaminB9: { min: 188 },
      vitaminB12: { min: 4.4 },
      choline: { min: 600 },
    },
    perDm: {
      crudeProtein: { min: 25 },
      crudeFat: { min: 9 },
      arginine: { min: 1 },
      histidine: { min: 0.26 },
      isoleucine: { min: 0.43 },
      leucine: { min: 1.02 },
      lysine: { min: 0.34 },
      methionine: { min: 0.17 },
      methionineCystine: { min: 0.34 },
      phenylalanine: { min: 0.4 },
      phenylalanineTyrosine: { min: 1.53 },
      threonine: { min: 0.52 },
      tryptophan: { min: 0.13 },
      valine: { min: 0.51 },
      taurine: { min: 0.1 },
      linoleicAcid: { min: 0.5 },
      arachidonicAcid: { min: 6 },
      calcium: { min: 0.4 },
      phosphorus: { min: 0.26 },
      potassium: { min: 0.6 },
      sodium: { min: 0.08 },
      chloride: { min: 0.11 },
      magnesium: { min: 0.04 },
      copper: { min: 0.5, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.13, max: 1.1, maxType: 'legal' },
      iron: { min: 8, max: 68.18, maxType: 'legal' },
      manganese: { min: 0.5, max: 17, maxType: 'legal' },
      selenium: { min: 21, max: 56.8, maxType: 'legal' },
      zinc: { min: 7.5, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 333 },
      vitaminD: { min: 25 },
      vitaminE: { min: 3.8 },
      vitaminB1: { min: 0.44 },
      vitaminB2: { min: 0.32 },
      vitaminB3: { min: 3.2 },
      vitaminB5: { min: 0.58 },
      vitaminB6: { min: 0.25 },
      vitaminB7: { min: 6 },
      vitaminB9: { min: 75 },
      vitaminB12: { min: 1.76 },
      choline: { min: 240 },
    },
    ratios: { caP: { min: 1, max: 2 } },
  },
  {
    id: 'FEDIAF_2025_CAT_GROWTH_REPRO',
    standard: 'FEDIAF', year: 2025, species: 'cat', lifeStage: 'early_growth_repro',
    label: '고양이 성장·번식',
    perMe: {
      crudeProtein: { min: 75 },
      crudeFat: { min: 22.5 },
      arginine: { min: 2.78 },
      histidine: { min: 0.83 },
      isoleucine: { min: 1.35 },
      leucine: { min: 3.2 },
      lysine: { min: 2.13 },
      methionine: { min: 1.1 },
      methionineCystine: { min: 2.2 },
      phenylalanine: { min: 1.25 },
      phenylalanineTyrosine: { min: 4.78 },
      threonine: { min: 1.63 },
      tryptophan: { min: 0.4 },
      valine: { min: 1.6 },
      taurine: { min: 0.25 },
      linoleicAcid: { min: 1.38 },
      arachidonicAcid: { min: 50 },
      alphaLinolenicAcid: { min: 0.05 },
      epaDha: { min: 0.03 },
      calcium: { min: 2.5 },
      phosphorus: { min: 2.1 },
      potassium: { min: 1.5 },
      sodium: { min: 0.4 },
      chloride: { min: 0.6 },
      magnesium: { min: 0.13 },
      copper: { min: 2.5 },
      iodine: { min: 0.45 },
      iron: { min: 20 },
      manganese: { min: 2.5 },
      selenium: { min: 75 },
      zinc: { min: 18.8 },
      vitaminA: { min: 2250 },
      vitaminD: { min: 70 },
      vitaminE: { min: 9.5 },
      vitaminB1: { min: 1.4 },
      vitaminB2: { min: 0.8 },
      vitaminB3: { min: 8 },
      vitaminB5: { min: 1.43 },
      vitaminB6: { min: 0.63 },
      vitaminB7: { min: 17.5 },
      vitaminB9: { min: 188 },
      vitaminB12: { min: 4.5 },
      choline: { min: 600 },
    },
    perDm: {
      crudeProtein: { min: 30 },
      crudeFat: { min: 9 },
      arginine: { min: 1.11 },
      histidine: { min: 0.33 },
      isoleucine: { min: 0.54 },
      leucine: { min: 1.28 },
      lysine: { min: 0.85 },
      methionine: { min: 0.44 },
      methionineCystine: { min: 0.88 },
      phenylalanine: { min: 0.5 },
      phenylalanineTyrosine: { min: 1.91 },
      threonine: { min: 0.65 },
      tryptophan: { min: 0.16 },
      valine: { min: 0.64 },
      taurine: { min: 0.1 },
      linoleicAcid: { min: 0.55 },
      arachidonicAcid: { min: 20 },
      alphaLinolenicAcid: { min: 0.02 },
      epaDha: { min: 0.01 },
      calcium: { min: 1 },
      phosphorus: { min: 0.84 },
      potassium: { min: 0.6 },
      sodium: { min: 0.16 },
      chloride: { min: 0.24 },
      magnesium: { min: 0.05 },
      copper: { min: 1, max: 2.8, maxType: 'legal' },
      iodine: { min: 0.18, max: 1.1, maxType: 'legal' },
      iron: { min: 8, max: 68.18, maxType: 'legal' },
      manganese: { min: 1, max: 17, maxType: 'legal' },
      selenium: { min: 30, max: 56.8, maxType: 'legal' },
      zinc: { min: 7.5, max: 22.7, maxType: 'legal' },
      vitaminA: { min: 900 },
      vitaminD: { min: 28 },
      vitaminE: { min: 3.8 },
      vitaminB1: { min: 0.55 },
      vitaminB2: { min: 0.32 },
      vitaminB3: { min: 3.2 },
      vitaminB5: { min: 0.57 },
      vitaminB6: { min: 0.25 },
      vitaminB7: { min: 7 },
      vitaminB9: { min: 75 },
      vitaminB12: { min: 1.8 },
      choline: { min: 240 },
    },
    ratios: { caP: { min: 1, max: 1.5 } },
  },
]
