import type { NutrientProfile } from '../../../types/recipe'

// NRC 2006 Nutrient Requirements (Adult Maintenance). 단계 1-A 확장 (DL-032).
// 자료원: 2006 NRC, Amount per 1000 kcal ME 표의 Recommended Allowance(RA).
// RA를 min으로 사용(개체 권장섭취량 — '완전사료 최소'인 FEDIAF/AAFCO와 의미가
// 약간 다름). 상한(max)은 정렬 불안정+FEDIAF/AAFCO가 제공하므로 생략. perMe만
// (NRC는 per-1000kcal만 제공). 단위 명확분만: sodium(원표 단위 오류 의심),
// vitaminA(RE)/D(mcg)/E(IU)/K(menadione)는 환산 애매로 생략. 단위 변환:
// chloride·magnesium mg→g, iodine mcg→mg, selenium·B9·B12 mcg→µg.

export const NRC_2006_PROFILES: NutrientProfile[] = [
  {
    id: 'NRC_2006_DOG_ADULT',
    standard: 'NRC', year: 2006, species: 'dog', lifeStage: 'adult',
    label: '성견 유지 (NRC 권장섭취량)',
    perMe: {
      crudeProtein: { min: 25 },
      crudeFat: { min: 13.8 },
      arginine: { min: 0.88 },
      histidine: { min: 0.48 },
      isoleucine: { min: 0.95 },
      leucine: { min: 1.7 },
      lysine: { min: 0.88 },
      methionine: { min: 0.83 },
      methionineCystine: { min: 1.63 },
      phenylalanine: { min: 1.13 },
      threonine: { min: 1.08 },
      tryptophan: { min: 0.35 },
      valine: { min: 1.23 },
      linoleicAcid: { min: 2.8 },
      alphaLinolenicAcid: { min: 0.11 },
      calcium: { min: 1 },
      phosphorus: { min: 0.75 },
      potassium: { min: 1 },
      chloride: { min: 0.3 },
      magnesium: { min: 0.15 },
      copper: { min: 1.5 },
      iodine: { min: 0.22 },
      iron: { min: 7.5 },
      manganese: { min: 1.2 },
      selenium: { min: 87.5 },
      zinc: { min: 15 },
      vitaminB1: { min: 0.56 },
      vitaminB2: { min: 1.3 },
      vitaminB3: { min: 4.25 },
      vitaminB5: { min: 3.75 },
      vitaminB6: { min: 0.375 },
      vitaminB9: { min: 67.5 },
      vitaminB12: { min: 8.75 },
      choline: { min: 425 },
    },
    perDm: {},
  },
  {
    id: 'NRC_2006_CAT_ADULT',
    standard: 'NRC', year: 2006, species: 'cat', lifeStage: 'adult',
    label: '성묘 유지 (NRC 권장섭취량)',
    perMe: {
      crudeProtein: { min: 50 },
      arginine: { min: 1.93 },
      histidine: { min: 0.65 },
      isoleucine: { min: 1.08 },
      leucine: { min: 2.55 },
      lysine: { min: 0.85 },
      methionine: { min: 0.43 },
      methionineCystine: { min: 0.85 },
      phenylalanine: { min: 1 },
      threonine: { min: 1.3 },
      tryptophan: { min: 0.33 },
      valine: { min: 1.28 },
      taurine: { min: 0.1 },
      linoleicAcid: { min: 1.4 },
      arachidonicAcid: { min: 0.015 },
      calcium: { min: 0.72 },
      phosphorus: { min: 0.64 },
      potassium: { min: 1.3 },
      chloride: { min: 0.24 },
      magnesium: { min: 0.1 },
      copper: { min: 1.2 },
      iodine: { min: 0.35 },
      iron: { min: 20 },
      manganese: { min: 1.2 },
      selenium: { min: 75 },
      zinc: { min: 18.5 },
      vitaminB1: { min: 1.4 },
      vitaminB2: { min: 1 },
      vitaminB3: { min: 10 },
      vitaminB5: { min: 1.44 },
      vitaminB6: { min: 0.625 },
      vitaminB9: { min: 188 },
      vitaminB12: { min: 5.6 },
      choline: { min: 637 },
    },
    perDm: {},
  },
]
